// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_PAGE11(lv_event_t * e);
extern lv_obj_t * ui_PAGE11;
extern lv_obj_t * ui_Label1;
void ui_event_PAGE21(lv_event_t * e);
extern lv_obj_t * ui_PAGE21;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_NEXT;
extern lv_obj_t * uic_NEXT1;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_PAGE22(lv_event_t * e);
extern lv_obj_t * ui_PAGE22;
extern lv_obj_t * ui_Label3;
void ui_event_MENU1(lv_event_t * e);
extern lv_obj_t * ui_MENU1;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BACK;
extern lv_obj_t * uic_BACK1;

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_PAGE1(lv_event_t * e);
extern lv_obj_t * ui_PAGE1;
extern lv_obj_t * ui_Label5;
void ui_event_MENU2(lv_event_t * e);
extern lv_obj_t * ui_MENU2;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
