// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PAGE1 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_PAGE1, 100);
    lv_obj_set_height(ui_PAGE1, 50);
    lv_obj_set_x(ui_PAGE1, 0);
    lv_obj_set_y(ui_PAGE1, -67);
    lv_obj_set_align(ui_PAGE1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PAGE1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PAGE1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 1);
    lv_obj_set_y(ui_Label5, -67);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "PAGE 1");

    ui_MENU2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_MENU2, 100);
    lv_obj_set_height(ui_MENU2, 50);
    lv_obj_set_align(ui_MENU2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MENU2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MENU2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "MENU");

    lv_obj_add_event_cb(ui_PAGE1, ui_event_PAGE1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MENU2, ui_event_MENU2, LV_EVENT_ALL, NULL);

}
